spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/multi_user_app
    username: postgres
    password: pgadmin
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9100
